SRC_TRG_TXT_DIC = {
    # Human face
    'tanned': (['face'],
               ['tanned face']),
    'pale': (['face'],
             ['pale face']),
    'makeup': (['person'],
               ['person with makeup']),
    'no_makeup': (['person'],
                  ['person without makeup']),
    'old': (['person'],
            ['old person']),
    'young': (['person'],
              ['young person']),
    'beards': (['person'],
               ['person with beards']),
    'angry': (['face'],
              ['angry face']),
    'surprised': (['face'],
                  ['surprised face']),
    'smiling': (['face'],
                ['smiling face']),
    'blond_hair': (['person'],
                   ['person with blond hair']),
    'red_hair': (['person'],
                 ['person with red hair']),
    'grey_hair': (['person'],
                  ['person with red hair']),
    'curly_hair': (['person'],
                   ['person with curly hair']),

    'nicolas': (['Person'],
                ['Nicolas Cage']),
    'zuckerberg': (['Person'],
                   ['Mark Zuckerberg']),
    'benedict': (['Person'],
              ['Benedict Cumberbatch']),
    'gogh': (['photo'],
             ['painting by Gogh']),
    'frida': (['photo'],
              ['self-portrait by Frida Kahlo']),
    'modigliani': (['photo'],
                   ['Painting in Modigliani style']),
    'sketch': (['photo'],
              ['sketch']),
    'watercolor': (['photo'],
                   ['Watercolor Art with Thick Brushstrokes']),
    'elf': (['Human'],
            ['Tolkien elf']),
    'super_saiyan': (['Human'],
                     ['Super saiyan']),
    'pixar': (['Human'],
              ['3D render in the style of Pixar']),
    'neanderthal': (['Human'],
                    ['Neanderthal']),
    'zombie': (['Human'],
               ['Zombie']),
    'jocker': (['Human'],
               ['The Jocker']),



}